### ISSUE TITLE
Concepts: add diagrams

### ISSUE THREAD

**Issue by cmjc** [autonity/docs.autonity.org#104]
### Description

Some concept explanations would be much reinforced if backed up by diagrams detailing the protocol activity flows.

Candidates are:

- Staking:
  - bonding  and unbonding flows
- ASM, CDP:
  - open (deposit) and service (repay, withdraw, deposit) flows
- Accountability (AFD):
  - accountability event, accusation, fault promotion and innocence flows
  - slashing penalty flow
- Validator:
  - lifecycle state transitions - see https://github.com/autonity/autonity/pull/1021#discussion_r1802597925
### Rationale

It will aid understanding by providing a visualisation of flow

### Implementation

**Tasks**:

Add diagrams to Concept pages for:

- Staking:
  - [ ] bonding flow
  - [ ] unbonding flow
- ASM, CDP:
  - [ ] open flow
  - [ ] repay flow
  - [ ] withdraw flow
  - [ ] liquidate flow
- Accountability (AFC):
  - [ ] accountability event detection and submission flow
  - [ ] accusation flow
  - [ ] fault promotion flow
  - [ ] innocence flow
  - [ ] slashing penalty flow
- Validator:
  - [ ] register, pause, reactivate flows
  - [ ] state transitions: active, pause, jailed states (0: active, 1:paused, 2:jailed)

### Related issues

- #7
