### ISSUE TITLE
Error in Reference genesis

### ISSUE THREAD

**Issue by jay-cousins** [autonity/docs.autonity.org#2]
**Describe the bug**

The entry for `treasuryFee` does not who the correct number of 0's for 10^18 in the example, and neither does the example `genesis.json`.

**Tasks to resolve**:

- [x] Update `treasuryFee` to use value in Autonity Testnet config.go: https://github.com/autonity/autonity/blob/a7ccfc1c5ac491cfafada845fd282e1549b8c749/params/config.go#L153
- [x] Check other entries in the genesis reference and ensure sync'd with above config for Bakerloo.
- [x] Update example `genesis.json` for `treasuryFee` and check other values.

**Device information (please complete the following information):**

- Device: Desktop
- OS: Mac OS Ventura 13.0.1
- Browser Chrome
- Browser Version 108.0.5359.124 (Official Build) (x86_64)
