### ISSUE TITLE
Update Runing an AOS to add install and run as (a) a daemon service, (b) a Docker image

### ISSUE THREAD

**Issue by jay-cousins** [autonity/docs.autonity.org#88]
### Description

The how to guide for install and running AOS documents how to run and install from binary or executable.

How to run as a docker image should be added.

### Tasks

- [x] Add "How to install as a Docker image"
- [x] Add "How to run as a Docker image"
- [ ] (Optional - documented in repo README) Add "How to run as a daemon service"

### References

- #75

**Comment by jay-cousins** [comment]
Running AOS as a Docker is documented in the linked PR.  

How to run as a daemon is documented in the AOS repo README, so leaving that to avoid duplication.
