### ISSUE TITLE
Update Network pages - check page up to date

### ISSUE THREAD

**Issue by jay-cousins** [autonity/docs.autonity.org#90]
### Description

The Network pages will need to be updated to record:

- Genesis configuration: oracle symbols and vote period
- Release: new autonity release version.
- Faucet: faucet details

### Tasks:

- Bakerloo:
  - [x] Genesis configuration: oracle symbols and vote period
  - [x] Release: new autonity release version
  - [x] Faucet: faucet details
- Piccadilly:
  - [x] Genesis configuration: oracle symbols and vote period
  - [x] Release: new autonity release version
  - [x] Faucet: faucet details
